apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
spec:
  selector:
    app: nginx       # Label selector to match pods with label "app: nginx"
  ports:
    - protocol: TCP
      port: 80       # Port on which the service will listen
      targetPort: 80 # Port on which the pods are listening
  type: LoadBalancer # Type of service - LoadBalancer
